language: c
sudo: false
dist: xenial

env:
  - CFLAGS="-Wall -W -O"

os:
  - linux

compiler:
  - clang
  - gcc
  - g++

arch:
  - arm64
  - amd64
  - s390x
  - ppc64le

matrix:
  include:
    - os: osx
      arch: amd64
      compiler: clang

addons:
  apt:
    packages:
      - p7zip-full

script:
  - make
  - make test
  - make clean
  - make -f Makefile.arduino package
