version: '3.3'

services:
  canary:
    image: canary:dev
    privileged: true
    volumes:
      - ./:/input/:rw
    command:
      - mutate
      - --base=/input
      - --file=impl/sign.h impl/secretbox.h impl/gimli-core/portable.h impl/random/windows.h impl/random/wasi.h impl/random/unix.h impl/random/riot.h impl/random/particle.h impl/random/nrf52832.h impl/random/avr.h
      - --out=./mutation_analysis
      - --build_command=make -C /input/ tests/tests
      - --test_command=/input/tests/tests
      - --placement_strategy=pathbased
      - --testing_backend=ffs_gnu_assert
      - --mutation_strategy=obom
      - --unit_blacklist=hydro_memzero hydro_compare hydro_kx_aead_final hydro_kx_aead_init hydro_kx_aead_xor_dec_3 hydro_kx_aead_xor_enc_2 hydro_pwhash_upgrade hydro_x25519_umaal hydro_x25519_adc0

# Batch 1


# random/windows.h
# --unit_blacklist=

# random/wasi.h
# --unit_blacklist=

# random/unix.h
# --unit_blacklist=

# random/riot.h
# --unit_blacklist=

# random/particle.h
# --unit_blacklist=

# random/nrf52832.h
# --unit_blacklist=

# random/avr.h
# --unit_blacklist=

# IMPOSSIBLE DUE TO AMOUNT OF CALLS
# gimli-core/sse2.h
# --unit_blacklist=

# gimli-core/portable.h
# --unit_blacklist=

# IMPOSSIBLE DUE TO AMOUNT OF CALLS
# x25519.h
# --unit_blacklist=

# sign.h
# --unit_blacklist=

# secretbox.h
# --unit_blacklist=

# random.h
# --unit_blacklist=

# pwhash.h
# --unit_blacklist=hydro_pwhash_upgrade
# hydro_pwhash_upgrade causes infinite loop

# kx.h
# --unit_blacklist=hydro_kx_aead_final hydro_kx_aead_init hydro_kx_aead_xor_dec_3 hydro_kx_aead_xor_enc_2

# core.h
# --unit_blacklist=hydro_memzero hydro_compare
# hydro_compare causes infinite loop


# Batch 1
# impl/hash.h impl/common.h
# --unit_whitelist=mem_cpy mem_xor mem_xor2 hydro_hash_init hydro_hash_init_with_tweak hydro_hash_final hydro_hash_hash hydro_hash_keygen

# hash.h
# - --unit_whitelist=hydro_hash_init hydro_hash_init_with_tweak hydro_hash_final hydro_hash_hash hydro_hash_keygen

# common.h
# --unit_whitelist=mem_cpy mem_xor mem_xor2
